version: '2.1'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1002
      - PGID=1002
      - TZ=Asia/Colombo
      - URL=cybergateservices.net
      - SUBDOMAINS=cybodo,
      - VALIDATION=http
      - EMAIL=cybererp@cybergateservices.net #optional
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=true #optional
      - STAGING=false #optional
    networks:
      cybererp-network:
        aliases:
          - letsencrypt
    volumes:
      - ./config/letsencrypt:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  postgresql:
    image: 'bitnami/postgresql:11'
    container_name: postgresql
    user: root
    command: chown -R 1001:1001 /bitnami
    environment:
      - POSTGRESQL_PASSWORD=cgdbadmin
    networks:
      cybererp-network:
        aliases:
          - postgresql
    volumes:
      - ./data/postgresql_data:/bitnami/postgresql
  odoo:
    image: 'bitnami/odoo:12'
    container_name: odoo
    ports:
      - 8069:8069
      - 8071:8071
    environment:
     - ODOO_PASSWORD=cgerpadmin
     - ODOO_MAIL=cgadmin@cybergateservices.net
     - POSTGRESQL_USER=odoo
     - POSTGRESQL_PASSWORD=cgdbadmin
     - POSTGRESQL_HOST=postgresql
     - POSTGRESQL_PORT_NUMBER=5432
    networks:
      cybererp-network:
        aliases:
          - odoo
    volumes:
      - ./data/odoo_data:/bitnami
    depends_on:
      - postgresql
      - letsencrypt
volumes:
  postgresql_data:
    driver: local
  odoo_data:
    driver: local
networks:
  cybererp-network:
    driver: bridge
