version: '2.1'
services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    hostname: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS},
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
      - DHLEVEL=${DHLEVEL}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
      - STAGING=${STAGING}
    networks:
      cybererp-network:
        aliases:
          - letsencrypt
    volumes:
      - ./conf/proxy/cadvisor.conf:/config/nginx/proxy-confs/cadvisor.subdomain.conf
      - ./conf/proxy/odoo.conf:/config/nginx/proxy-confs/odoo.subdomain.conf
      - ./conf/proxy/pgadmin.conf:/config/nginx/proxy-confs/pgadmin.subdomain.conf
      - ./conf/proxy/prometheus.conf:/config/nginx/proxy-confs/prometheus.subdomain.conf
      - ./conf/htpasswd:/config/nginx/.htpasswd:rw
    ports:
      - 443:443
      - 80:80 #optional
    restart: always
  postgresql:
    image: postgres:10
    container_name: postgresql
    hostname: postgresql
    environment:
       - POSTGRES_DB=${POSTGRES_DB}
       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
       - POSTGRES_USER=${POSTGRES_USER}
       - PGDATA=${PGDATA}
    networks:
      cybererp-network:
        aliases:
          - postgresql
    volumes:
      - postgresql_data:/var/lib/postgresql/data/pgdata
    restart: always
  odoo:
    image: odoo:12.0
    container_name: odoo
    hostname: odoo
    # command: --database odoo -i base
    environment:
      - HOST=postgresql
      - USER=${ODOO_USER}
      - PASSWORD=${ODOO_PASSWORD}
    networks:
      cybererp-network:
        aliases:
          - odoo
    volumes:
      - odoo_data:/var/lib/odoo
      - ./conf/odoo:/etc/odoo
      - ./addons:/mnt/extra-addons
    depends_on:
      - postgresql
      - letsencrypt
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    hostname: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    # ports:
    #  - "10080:80"
    depends_on:
      - postgresql
    networks:
      cybererp-network:
        aliases:
         - pgadmin
    restart: always
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
    networks:
      cybererp-network:
        aliases:
         - prometheus
    restart: always
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor 
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    networks:
      cybererp-network:
        aliases:
         - cadvisor
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports: 
      - 6379:6379
    networks:
      cybererp-network:
        aliases:
         - redis
    restart: always
volumes:
  postgresql_data:
  odoo_data: 
networks:
  cybererp-network:
    driver: bridge
